---
abstract: 'Scripting www.ruten.com.tw'
author:
  - 'Kang-min Liu <gugod@gugod.org>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300000, CPAN::Meta::Converter version 2.112150'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Ruten
requires:
  Encode: 0
  HTML::Selector::XPath: 0
  HTML::TreeBuilder::XPath: 0
  WWW::Mechanize: 1.66
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/gugod/WWW-Ruten/issues
  repository: git://github.com/gugod/www-ruten.git
version: 0.03
